// Gerado a partir do áudio real: cada frase é um arquivo separado,
// então início e fim de cada legenda (e de cada plano) são exatos.
export const FPS = 30;
export const TOTAL_FRAMES = 21728;

export const LINES = [
  { from: 24, durationInFrames: 222, text: "On the eighteenth of June, 2020, a group of auditors refused to sign a document." },
  { from: 246, durationInFrames: 228, text: "That refusal ended a company that, eighteen months earlier, had been worth more than Deutsche Bank." },
  { from: 474, durationInFrames: 134, text: "The reason was simple, and almost impossible to believe." },
  { from: 608, durationInFrames: 101, text: "One point nine billion euros were missing." },
  { from: 709, durationInFrames: 97, text: "Not misplaced. Not frozen. Missing." },
  { from: 806, durationInFrames: 156, text: "That money was roughly a quarter of everything Wirecard claimed to own." },
  { from: 962, durationInFrames: 174, text: "And within days, the company would admit the cash had probably never existed at all." },
  { from: 1136, durationInFrames: 192, text: "This is how Germany's most celebrated technology company turned out to be a crime scene." },
  { from: 1328, durationInFrames: 182, text: "And how the people who tried to warn everyone were the ones investigated first." },
  { from: 1510, durationInFrames: 148, text: "To understand the fall, you have to understand how high it got." },
  { from: 1658, durationInFrames: 246, text: "Wirecard started in 1999, processing online payments out of a suburb of Munich." },
  { from: 1904, durationInFrames: 185, text: "For most of its life it was a middleman, taking a small cut of card transactions." },
  { from: 2089, durationInFrames: 232, text: "Unglamorous work. Enormous volume. A business almost nobody outside finance thought about." },
  { from: 2321, durationInFrames: 208, text: "Then, through the twenty tens, it started growing faster than anything else in German technology." },
  { from: 2529, durationInFrames: 154, text: "Acquisitions across Asia. Revenue climbing every single quarter." },
  { from: 2683, durationInFrames: 172, text: "A share price that behaved less like a payments company and more like a tech stock." },
  { from: 2855, durationInFrames: 281, text: "On the twenty fourth of September, 2018, Wirecard entered the DAX, Germany's blue chip index." },
  { from: 3136, durationInFrames: 201, text: "It took the seat of Commerzbank, a bank founded in 1870." },
  { from: 3337, durationInFrames: 213, text: "A hundred and forty eight years of banking history, replaced by a payments firm from the suburbs." },
  { from: 3550, durationInFrames: 219, text: "At that moment, Wirecard was valued at around twenty four point six billion euros." },
  { from: 3769, durationInFrames: 139, text: "That was more than Deutsche Bank, the largest lender in the country." },
  { from: 3908, durationInFrames: 123, text: "Analysts called it the German answer to Silicon Valley." },
  { from: 4031, durationInFrames: 163, text: "Politicians pointed at it as proof that Europe could still build something." },
  { from: 4194, durationInFrames: 136, text: "For German finance, this was a national success story." },
  { from: 4330, durationInFrames: 210, text: "And nobody wanted to look too closely at a national success story." },
  { from: 4540, durationInFrames: 91, text: "Now, the part that actually broke." },
  { from: 4631, durationInFrames: 227, text: "A large share of Wirecard's business supposedly ran through what it called third party acquirers." },
  { from: 4858, durationInFrames: 290, text: "The logic sounded reasonable. In countries where Wirecard did not hold a licence, local partners processed payments on its behalf." },
  { from: 5148, durationInFrames: 138, text: "Wirecard booked the profits from those partners as its own." },
  { from: 5286, durationInFrames: 180, text: "And those profits, the company said, sat in trustee accounts in the Philippines." },
  { from: 5466, durationInFrames: 186, text: "Money the company owned, held by someone else, ten thousand kilometres away." },
  { from: 5652, durationInFrames: 172, text: "On the balance sheet, that was one point nine billion euros of cash." },
  { from: 5824, durationInFrames: 80, text: "Here is what matters about that number." },
  { from: 5904, durationInFrames: 291, text: "It was not a side business. Analysts estimated the third party operation generated the majority of Wirecard's reported profit." },
  { from: 6195, durationInFrames: 211, text: "So the most important part of the company was also the part nobody outside could actually see." },
  { from: 6406, durationInFrames: 183, text: "Confirming cash that size normally means asking the bank that holds it, directly." },
  { from: 6589, durationInFrames: 200, text: "The documents that were supposed to prove these balances later turned out to be forgeries." },
  { from: 6789, durationInFrames: 106, text: "Which brings us to a lawyer in Singapore." },
  { from: 6895, durationInFrames: 123, text: "Pav Gill worked in Wirecard's legal department there." },
  { from: 7018, durationInFrames: 198, text: "He started looking into what appeared to be manipulated accounts and fictitious transactions." },
  { from: 7216, durationInFrames: 152, text: "According to his account, his internal investigation was shut down." },
  { from: 7368, durationInFrames: 97, text: "So he took the documents somewhere else." },
  { from: 7465, durationInFrames: 235, text: "They reached Dan McCrum, a reporter at the Financial Times, who had been examining Wirecard's accounting for years." },
  { from: 7700, durationInFrames: 99, text: "And the Financial Times began publishing." },
  { from: 7799, durationInFrames: 227, text: "In February 2019, Singapore police raided Wirecard's offices in the city." },
  { from: 8026, durationInFrames: 213, text: "At that point, this was no longer a reporter's theory. It was a police matter in a second country." },
  { from: 8239, durationInFrames: 160, text: "Singapore prosecutors would later bring charges connected to the case." },
  { from: 8399, durationInFrames: 172, text: "A businessman linked to the scheme was sentenced to twelve months in jail." },
  { from: 8571, durationInFrames: 202, text: "And the executive investigators named as the architect of the Asian accounting was never caught." },
  { from: 8773, durationInFrames: 205, text: "An Interpol red notice was issued for him. He remains at large." },
  { from: 8978, durationInFrames: 140, text: "What happened next is the part of this story that should worry you the most." },
  { from: 9118, durationInFrames: 114, text: "Wirecard did not simply deny the reporting." },
  { from: 9232, durationInFrames: 226, text: "The company said it was the victim of market manipulation, of short sellers working together with journalists." },
  { from: 9458, durationInFrames: 170, text: "And Germany's financial regulator, BaFin, took the company's side." },
  { from: 9628, durationInFrames: 171, text: "In February 2019, BaFin did two things at the same time." },
  { from: 9799, durationInFrames: 159, text: "First, it banned short selling of Wirecard shares for two months." },
  { from: 9958, durationInFrames: 190, text: "That had never happened before. Not once, for a single company, in the regulator's history." },
  { from: 10148, durationInFrames: 243, text: "Second, it filed criminal complaints against the Financial Times journalists investigating the company." },
  { from: 10391, durationInFrames: 169, text: "Read that again. The regulator shielded the company, and went after the reporters." },
  { from: 10560, durationInFrames: 184, text: "Think about what that signals to every other analyst, investor and journalist watching." },
  { from: 10744, durationInFrames: 205, text: "Questioning Wirecard was now, officially, the suspicious activity." },
  { from: 10949, durationInFrames: 254, text: "The company then hired KPMG to run a special audit, specifically to prove the Financial Times wrong." },
  { from: 11203, durationInFrames: 144, text: "The report arrived in April 2020, and it did not do that." },
  { from: 11347, durationInFrames: 133, text: "KPMG said it could not verify the third party business." },
  { from: 11480, durationInFrames: 174, text: "It flagged weaknesses in record keeping at a regulated financial institution." },
  { from: 11654, durationInFrames: 117, text: "And it raised new questions nobody had asked before." },
  { from: 11771, durationInFrames: 164, text: "An audit commissioned to close the story had just extended it." },
  { from: 11935, durationInFrames: 147, text: "Two months later, the ending arrived, and it took seven days." },
  { from: 12082, durationInFrames: 174, text: "June eighteenth. Ernst and Young refuses to sign off on the annual accounts." },
  { from: 12256, durationInFrames: 209, text: "The stated reason is that it cannot confirm the existence of one point nine billion euros." },
  { from: 12465, durationInFrames: 250, text: "The stock falls as much as sixty seven percent in a single session. The worst day in the company's history." },
  { from: 12715, durationInFrames: 201, text: "June nineteenth. Markus Braun, chief executive for eighteen years, resigns." },
  { from: 12916, durationInFrames: 135, text: "The same day, two Philippine banks make a statement of their own." },
  { from: 13051, durationInFrames: 238, text: "BDO Unibank and the Bank of the Philippine Islands say the documents supposedly proving those accounts were falsified." },
  { from: 13289, durationInFrames: 169, text: "One of them said the papers carried forged signatures of its own bank officers." },
  { from: 13458, durationInFrames: 192, text: "The paperwork behind a quarter of a DAX company's balance sheet was fake." },
  { from: 13650, durationInFrames: 121, text: "June twenty second. Wirecard issues a statement." },
  { from: 13771, durationInFrames: 189, text: "The one point nine billion euros, it says, probably does not exist." },
  { from: 13960, durationInFrames: 122, text: "Not lost. Not stolen in transit. Never there." },
  { from: 14082, durationInFrames: 203, text: "June twenty third. Markus Braun is arrested, accused of inflating the balance sheet." },
  { from: 14285, durationInFrames: 178, text: "June twenty fifth. Wirecard files for insolvency in a Munich court." },
  { from: 14463, durationInFrames: 203, text: "It becomes the first company in the history of the DAX to fail while sitting in the index." },
  { from: 14666, durationInFrames: 152, text: "Across the scandal, the share price fell more than ninety percent." },
  { from: 14818, durationInFrames: 178, text: "Roughly seventeen billion euros of market value simply stopped existing." },
  { from: 14996, durationInFrames: 194, text: "Pension funds held it. Index funds held it, automatically, because it was in the DAX." },
  { from: 15190, durationInFrames: 162, text: "Ordinary savers who had never heard the name Wirecard owned a piece of it." },
  { from: 15352, durationInFrames: 155, text: "That is what index investing means when the index itself is wrong." },
  { from: 15507, durationInFrames: 207, text: "The central bank of the Philippines confirmed the money never entered the country's financial system." },
  { from: 15714, durationInFrames: 171, text: "It later barred two bank employees connected to the fraud from working in finance." },
  { from: 15885, durationInFrames: 129, text: "But the people who lost money were never going to be made whole." },
  { from: 16014, durationInFrames: 252, text: "The insolvency administrator was left selling the pieces of a company whose largest asset had been imaginary." },
  { from: 16266, durationInFrames: 264, text: "Ernst and Young, the auditor that had signed Wirecard's accounts for years, described it as a sophisticated global fraud." },
  { from: 16530, durationInFrames: 166, text: "Which raises the obvious question about how many years it went unnoticed." },
  { from: 16696, durationInFrames: 183, text: "Ernst and Young had audited Wirecard for roughly a decade before the collapse." },
  { from: 16879, durationInFrames: 156, text: "In every one of those years, the accounts were signed." },
  { from: 17035, durationInFrames: 113, text: "And there is one person still missing from this story." },
  { from: 17148, durationInFrames: 206, text: "Jan Marsalek, the chief operating officer, the executive who ran the Asian business." },
  { from: 17354, durationInFrames: 142, text: "He was suspended, then dismissed, and then he was simply gone." },
  { from: 17496, durationInFrames: 174, text: "He is reported to have fled to Moscow. German police still list him as wanted." },
  { from: 17670, durationInFrames: 255, text: "In September 2020, German prosecutors dropped the investigation into the Financial Times journalists." },
  { from: 17925, durationInFrames: 171, text: "The reporting, it turned out, had been fundamentally accurate the entire time." },
  { from: 18096, durationInFrames: 167, text: "In December 2022, Markus Braun went on trial in Munich." },
  { from: 18263, durationInFrames: 205, text: "Prosecutors describe it as the largest accounting fraud in German corporate history." },
  { from: 18468, durationInFrames: 217, text: "Braun denies wrongdoing. A verdict is expected in 2026." },
  { from: 18685, durationInFrames: 239, text: "Sixteen months passed between the regulator filing complaints against those reporters and the company collapsing." },
  { from: 18924, durationInFrames: 207, text: "Sixteen months in which the warning was public, documented, and officially treated as the crime." },
  { from: 19131, durationInFrames: 161, text: "Germany rewrote parts of its financial supervision rules afterwards." },
  { from: 19292, durationInFrames: 154, text: "BaFin's leadership was replaced. The audit market was reformed." },
  { from: 19446, durationInFrames: 248, text: "The Financial Times went on to win awards for the reporting that the regulator had tried to criminalise." },
  { from: 19694, durationInFrames: 134, text: "But the deeper lesson here is not really about German regulation." },
  { from: 19828, durationInFrames: 185, text: "It is about what happens when a country decides in advance which story it wants to be true." },
  { from: 20013, durationInFrames: 95, text: "Wirecard was not hidden in a basement." },
  { from: 20108, durationInFrames: 181, text: "It was audited, listed, regulated, celebrated and covered by the press." },
  { from: 20289, durationInFrames: 154, text: "Every institution built to catch something like this had access to it." },
  { from: 20443, durationInFrames: 109, text: "And each one, in its own way, looked away." },
  { from: 20552, durationInFrames: 113, text: "The fraud did not survive because it was sophisticated." },
  { from: 20665, durationInFrames: 178, text: "It survived because questioning it was more expensive than believing it." },
  { from: 20843, durationInFrames: 151, text: "Wirecard is not really a story about one company that lied." },
  { from: 20994, durationInFrames: 139, text: "It is a story about how many people it takes to believe a lie," },
  { from: 21133, durationInFrames: 115, text: "and how expensive it becomes to be the one person who does not." },
];
