// Tempos derivados do áudio real: cada frase foi sintetizada em
// arquivo separado, então legenda e corte de cena caem exatos.
export const FPS = 30;
export const TOTAL_FRAMES = 13058;

export const SCENES = [
  { name: "ColdOpen", from: 12, durationInFrames: 592 },
  { name: "MissingMoney", from: 604, durationInFrames: 545 },
  { name: "TitleCard", from: 1149, durationInFrames: 356 },
  { name: "RiseTimeline", from: 1505, durationInFrames: 800 },
  { name: "DaxMoment", from: 2305, durationInFrames: 1148 },
  { name: "MoneyFlow", from: 3453, durationInFrames: 1302 },
  { name: "Journalist", from: 4755, durationInFrames: 1079 },
  { name: "RegulatorTurns", from: 5834, durationInFrames: 1237 },
  { name: "SpecialAudit", from: 7071, durationInFrames: 826 },
  { name: "SevenDays", from: 7897, durationInFrames: 1799 },
  { name: "CollapseStats", from: 9696, durationInFrames: 316 },
  { name: "NeverArrived", from: 10012, durationInFrames: 406 },
  { name: "StillMissing", from: 10418, durationInFrames: 607 },
  { name: "SixteenMonths", from: 11025, durationInFrames: 820 },
  { name: "Aftermath", from: 11845, durationInFrames: 296 },
  { name: "Closing", from: 12141, durationInFrames: 917 },
] as const;

export const CAPTIONS = [
  { from: 12, durationInFrames: 253, text: "On the eighteenth of June, 2020, a group of auditors at Ernst and Young refused to sign a document." },
  { from: 265, durationInFrames: 206, text: "That refusal ended a company that, eighteen months earlier, had been worth more than Deutsche Bank." },
  { from: 471, durationInFrames: 133, text: "The reason was simple, and almost impossible to believe." },
  { from: 604, durationInFrames: 105, text: "One point nine billion euros were missing." },
  { from: 709, durationInFrames: 102, text: "Not misplaced. Not frozen. Missing." },
  { from: 811, durationInFrames: 160, text: "That money represented roughly a quarter of everything Wirecard claimed to own." },
  { from: 971, durationInFrames: 178, text: "And within days, the company would admit the cash had probably never existed at all." },
  { from: 1149, durationInFrames: 185, text: "This is how Germany's most celebrated technology company turned out to be a crime scene." },
  { from: 1334, durationInFrames: 171, text: "And how the people who tried to warn everyone were the ones investigated first." },
  { from: 1505, durationInFrames: 234, text: "Wirecard started in 1999, processing online payments out of a suburb of Munich." },
  { from: 1739, durationInFrames: 188, text: "For most of its life, it was an unremarkable middleman, taking a cut of card transactions." },
  { from: 1927, durationInFrames: 193, text: "Then, in the twenty tens, it started growing faster than anything else in German technology." },
  { from: 2120, durationInFrames: 185, text: "Acquisitions across Asia. Revenue climbing every quarter. A stock that would not stop rising." },
  { from: 2305, durationInFrames: 260, text: "On the twenty fourth of September, 2018, Wirecard entered the DAX, Germany's blue chip index." },
  { from: 2565, durationInFrames: 179, text: "It took the place of Commerzbank, a bank founded in 1870." },
  { from: 2744, durationInFrames: 198, text: "At that moment, Wirecard was valued at around twenty four point six billion euros." },
  { from: 2942, durationInFrames: 114, text: "More than Deutsche Bank, the largest lender in the country." },
  { from: 3056, durationInFrames: 176, text: "A payments company from the Munich suburbs was now worth more than Germany's biggest bank." },
  { from: 3232, durationInFrames: 221, text: "For German finance, this was a national success story. And nobody wanted to look too closely at it." },
  { from: 3453, durationInFrames: 151, text: "To understand what broke, you have to understand one piece of the structure." },
  { from: 3604, durationInFrames: 206, text: "A large share of Wirecard's business supposedly ran through what it called third party acquirers." },
  { from: 3810, durationInFrames: 170, text: "These were outside partners in Asia that processed payments on Wirecard's behalf." },
  { from: 3980, durationInFrames: 187, text: "And the profits from that business, Wirecard said, sat in trustee accounts in the Philippines." },
  { from: 4167, durationInFrames: 173, text: "Money the company owned, held by someone else, on the other side of the world." },
  { from: 4340, durationInFrames: 152, text: "On the balance sheet, that was one point nine billion euros of cash." },
  { from: 4492, durationInFrames: 183, text: "The most important number in the company was also the hardest number for anyone to actually see." },
  { from: 4675, durationInFrames: 80, text: "Which brings us to the journalist." },
  { from: 4755, durationInFrames: 265, text: "Dan McCrum, a reporter at the Financial Times, had been investigating Wirecard's accounting since the middle of the twenty tens." },
  { from: 5020, durationInFrames: 114, text: "He had documents. He had a whistleblower in Singapore." },
  { from: 5134, durationInFrames: 278, text: "And over several years, the Financial Times published a series of reports on irregularities inside the company's Asian operations." },
  { from: 5412, durationInFrames: 137, text: "What happened next is the part of this story that should worry you the most." },
  { from: 5549, durationInFrames: 85, text: "Wirecard did not just deny the reporting." },
  { from: 5634, durationInFrames: 200, text: "The company said it was the victim of market manipulation, of short sellers working with journalists." },
  { from: 5834, durationInFrames: 153, text: "And Germany's financial regulator, BaFin, agreed with the company." },
  { from: 5987, durationInFrames: 158, text: "In February 2019, BaFin did two things at the same time." },
  { from: 6145, durationInFrames: 148, text: "First, it banned short selling of Wirecard shares for two months." },
  { from: 6293, durationInFrames: 173, text: "That had never happened before. Not once, for a single company, in the regulator's history." },
  { from: 6466, durationInFrames: 225, text: "Second, it filed criminal complaints against the Financial Times journalists who were investigating the company." },
  { from: 6691, durationInFrames: 178, text: "Read that again. The regulator protected the company, and went after the reporters." },
  { from: 6869, durationInFrames: 202, text: "The market took the hint. Questioning Wirecard was now, officially, the suspicious activity." },
  { from: 7071, durationInFrames: 231, text: "The company then hired KPMG to run a special audit, specifically to prove the Financial Times wrong." },
  { from: 7302, durationInFrames: 138, text: "The report landed in April 2020, and it did not do that." },
  { from: 7440, durationInFrames: 201, text: "KPMG said it could not verify the third party business. It flagged weaknesses in record keeping." },
  { from: 7641, durationInFrames: 113, text: "And it raised new questions that had not been asked before." },
  { from: 7754, durationInFrames: 143, text: "A special audit commissioned to end the story had just extended it." },
  { from: 7897, durationInFrames: 133, text: "Two months later, the ending arrived in seven days." },
  { from: 8030, durationInFrames: 160, text: "June eighteenth. Ernst and Young refuses to sign off on the annual accounts." },
  { from: 8190, durationInFrames: 192, text: "The reason given is that it cannot confirm the existence of one point nine billion euros." },
  { from: 8382, durationInFrames: 225, text: "The stock falls as much as sixty seven percent in a single session, the worst day in the company's history." },
  { from: 8607, durationInFrames: 177, text: "June nineteenth. Markus Braun, chief executive for eighteen years, resigns." },
  { from: 8784, durationInFrames: 106, text: "June twenty second. Wirecard issues a statement." },
  { from: 8890, durationInFrames: 176, text: "The one point nine billion euros, it says, probably does not exist." },
  { from: 9066, durationInFrames: 131, text: "Not lost. Not stolen in transit. Never there." },
  { from: 9197, durationInFrames: 192, text: "June twenty third. Markus Braun is arrested, accused of inflating the balance sheet." },
  { from: 9389, durationInFrames: 157, text: "June twenty fifth. Wirecard files for insolvency in a Munich court." },
  { from: 9546, durationInFrames: 150, text: "It becomes the first company in the history of the DAX to fail while in the index." },
  { from: 9696, durationInFrames: 144, text: "Over the course of the scandal, the share price fell more than ninety percent." },
  { from: 9840, durationInFrames: 172, text: "Roughly seventeen billion euros in market value simply stopped existing." },
  { from: 10012, durationInFrames: 200, text: "And the money? The central bank of the Philippines said the funds never entered the country's financial system." },
  { from: 10212, durationInFrames: 206, text: "The trustee accounts that held a quarter of Wirecard's balance sheet appear to have been a fiction." },
  { from: 10418, durationInFrames: 110, text: "There is one person still missing from this story." },
  { from: 10528, durationInFrames: 197, text: "Jan Marsalek, the chief operating officer, the executive who ran the Asian business." },
  { from: 10725, durationInFrames: 121, text: "He was suspended, then dismissed, and then he was gone." },
  { from: 10846, durationInFrames: 179, text: "He fled, reportedly to Moscow, and as of today he has not been found." },
  { from: 11025, durationInFrames: 237, text: "In September 2020, German prosecutors dropped the investigation into the Financial Times journalists." },
  { from: 11262, durationInFrames: 162, text: "The reporting, it turned out, had been fundamentally accurate the entire time." },
  { from: 11424, durationInFrames: 213, text: "Sixteen months passed between the regulator filing complaints against those reporters and the company collapsing." },
  { from: 11637, durationInFrames: 208, text: "Sixteen months in which the warning was public, documented, and officially treated as the crime." },
  { from: 11845, durationInFrames: 142, text: "Germany rewrote parts of its financial supervision rules after this." },
  { from: 11987, durationInFrames: 154, text: "BaFin's leadership was replaced. The audit market was reformed." },
  { from: 12141, durationInFrames: 103, text: "But the deeper lesson is not about German regulation." },
  { from: 12244, durationInFrames: 182, text: "It is about what happens when a country decides in advance which story it wants to be true." },
  { from: 12426, durationInFrames: 175, text: "Wirecard was not hidden. It was audited, listed, regulated, and celebrated." },
  { from: 12601, durationInFrames: 155, text: "Every institution built to catch this had access to it, and looked away." },
  { from: 12756, durationInFrames: 113, text: "The fraud did not survive because it was sophisticated." },
  { from: 12869, durationInFrames: 123, text: "It survived because questioning it was more expensive than believing it." },
];
