export const LINES = {
  "cap1": [
    "Thirty seconds were left before the meeting started.",
    "One click. That's all it would take.",
    "One click, and the entire company would change hands.",
    "Marcus stared at the button glowing on the screen.",
    "Sign contract. The cursor blinking right on top of the word, patient, almost mocking him.",
    "His hand was resting on the trackpad, not moving.",
    "He didn't know it yet, but in less than a minute,",
    "he was about to make the most expensive decision of his life.",
    "Before I tell you what happened when he finally clicked,",
    "let me back up. Because to understand why that single click mattered so much,",
    "you need to understand how this company was born in the first place,",
    "and how far it had come to end up in that room.",
    "Ten years earlier,",
    "Marcus and Richard were just two friends in their twenties with a borrowed",
    "laptop, a stubborn idea, and absolutely no money.",
    "Their plan was a simple management system for small stores,",
    "something to help mom-and-pop shops track inventory without paying for expensive enterprise software.",
    "Nobody believed in it. The banks turned them down, twice.",
    "Their own families thought they were wasting their time.",
    "But the two of them kept their day jobs to pay rent,",
    "and at night, in Richard's mother's garage,",
    "surrounded by boxes and a space heater that barely worked,",
    "they built what would eventually become Nortech.",
    "The first three years brought no profit at all.",
    "The two after that nearly buried them,",
    "more than once they came within days of shutting it all down.",
    "But slowly, painfully, one client at a time,",
    "Nortech turned into a real company.",
    "Forty employees. Its own office downtown.",
    "Contracts with stores across eight different states.",
    "Marcus took care of the product, the code,",
    "the late nights fixing bugs nobody else even noticed.",
    "Richard took care of the money and the big clients, the handshakes,",
    "the deals, the relationships that kept the lights on.",
    "It was a partnership that worked,",
    "and it worked because one of them trusted the other completely,",
    "without ever really checking. But blind trust, when it finally breaks,",
    "doesn't break a little at a time.",
    "It breaks all at once.",
    "Their very first real client was a hardware store two towns over,",
    "a small family business that agreed to try the system for free for",
    "a month, just to see if it actually worked.",
    "It did. Word spread slowly, one shop owner telling another,",
    "and within a year they had thirty paying customers who trusted a product",
    "built by two guys who still,",
    "technically, worked out of a garage.",
    "Marcus still remembers the day they signed their first contract worth real money.",
    "Richard had printed it out just to hold the paper in his hands,",
    "laughing, saying this was the proof that all those sleepless nights hadn't been for",
    "nothing. They celebrated with gas station coffee because that's all they could afford,",
    "and it tasted, Marcus always says,",
    "like the best coffee of his entire life."
  ],
  "cta": [
    "Oh, and before we go any further, welcome to the channel.",
    "If this story already has you hooked,",
    "now's a good time to hit like and ring that little bell,",
    "because there's a brand new story just like this one dropping every single",
    "week, and trust me, you don't want to miss how this one ends.",
    "Alright. Back to Marcus."
  ],
  "cap2": [
    "Over the following two years, something in the company slowly started to shift.",
    "Nothing dramatic, nothing anyone could point to and say, there, that's the problem.",
    "Just small things. Richard traveled more than he used to.",
    "He took calls outside the office, always stepping into the hallway,",
    "always closing the door behind him.",
    "He showed up late to meetings that he himself had scheduled,",
    "sometimes without much of an explanation at all.",
    "Marcus noticed. Of course he noticed.",
    "But he pushed the doubt down, buried it under ten years of history.",
    "You don't throw away a decade of friendship over a few strange phone",
    "calls and a couple of missed meetings.",
    "People go through things. Maybe it was personal.",
    "Maybe it was nothing. Then came a Friday night that changed everything.",
    "Marcus had stayed late, alone in the office,",
    "finishing a financial report that was due first thing Monday.",
    "Everyone else had already gone home.",
    "That's when he saw it, completely by accident,",
    "an email left open on the shared executive computer,",
    "the same machine both of them used to review and sign documents.",
    "The subject line read: Acquisition proposal.",
    "Confidential. It didn't make any sense.",
    "Nortech had never opened a single conversation about being sold.",
    "Not to investors, not to competitors, not to anyone.",
    "Curious, and a little uneasy, Marcus clicked it open.",
    "And the name listed as the sole recipient wasn't his.",
    "It was Richard's. Only Richard's.",
    "No partner negotiates the sale of his own company behind the other partner's",
    "back. Not unless he has a very good reason to keep it hidden.",
    "Marcus closed the laptop slowly.",
    "He didn't call Richard that night.",
    "He didn't send an angry text.",
    "He needed to understand exactly how deep this went before he said a",
    "single word out loud. So over the weekend, alone at his kitchen table,",
    "he went through everything he still had access to.",
    "Old contracts. Years of emails.",
    "Every cash flow spreadsheet he could find.",
    "And buried in the numbers,",
    "he found a pattern: a string of transfers Richard had been quietly authorizing,",
    "month after month,",
    "to an outside consulting firm nobody in the office had ever heard of.",
    "The payments kept growing. Eight months of it, getting bigger every time.",
    "Three hundred thousand dollars, in total,",
    "had already left the company's account for a firm that, on paper,",
    "provided no visible service to Nortech whatsoever.",
    "Something was very wrong here.",
    "And somewhere deep down, Marcus already knew it.",
    "Monday morning, he'd have to ask the question directly.",
    "And he had a sinking feeling he wasn't going to like the answer.",
    "It wasn't just Marcus who noticed something was off.",
    "Two of the senior engineers had quietly started asking each other why Richard",
    "kept rescheduling the quarterly budget review,",
    "three times in a row now.",
    "Nobody said anything out loud.",
    "In a company that size, everyone still felt like family,",
    "and nobody wants to be the person who accuses a founder of anything",
    "without proof. At one point, Marcus tried calling Richard directly, late on a Wednesday,",
    "just to ask, casually, if everything was alright.",
    "Richard picked up, sounding distracted, background noise Marcus couldn't quite place,",
    "and said everything was fine, just some personal stuff, nothing to worry about.",
    "Marcus wanted to believe him.",
    "He almost did. Let's pause here for a second,",
    "because it's worth understanding what was actually at stake.",
    "Nortech wasn't some faceless corporation.",
    "It was forty mortgages, forty grocery bills,",
    "forty families who had no idea that a decision being made quietly behind",
    "closed doors could reshape their entire year.",
    "Marcus knew that.",
    "It's exactly why he didn't just storm into Richard's office that Friday night,",
    "and why, instead, he spent an entire weekend building a case, quietly, methodically,",
    "the same way he'd debug a piece of code that refused to behave.",
    "Find the actual problem before you touch anything."
  ],
  "cap3": [
    "Monday morning, before a single other meeting could get in the way,",
    "Marcus called Richard into his office and shut the door.",
    "I need you to explain something to me, he said,",
    "sliding the printed pages across the table.",
    "Three hundred thousand dollars, sent to a consulting firm nobody here has ever worked with.",
    "And an email about selling this company, addressed only to you.",
    "Richard looked at the papers.",
    "He didn't reach for them.",
    "He just sat there, silent, for one second too long,",
    "the kind of silence that already answers the question before anyone says a",
    "word. I was going to tell you, he finally said, quietly.",
    "I just didn't know how.",
    "And then, slowly, the whole story came out.",
    "Richard had invested, entirely on his own, in another startup,",
    "one Marcus had never even heard of.",
    "He hadn't told his partner.",
    "He hadn't involved Nortech at all.",
    "He genuinely believed it would pay off fast,",
    "that he'd quietly put the money back before anyone ever noticed a thing.",
    "It didn't pay off. The startup collapsed within months,",
    "and Richard was left owing a serious amount of money to the very",
    "firm that had backed his investment in the first place,",
    "the same firm now disguised on Nortech's books as a consultant.",
    "To cover that debt, he'd started quietly pulling money out of Nortech's own cash reserves,",
    "month after month, dressed up as legitimate consulting fees so no one would ask questions.",
    "And the sale email? That was the exit plan.",
    "Sell Nortech to an outside investor group,",
    "use the sale money to finally settle the debt,",
    "and disappear from the mess before Marcus ever found out what had really",
    "happened. Marcus didn't raise his voice.",
    "That's never been who he is.",
    "But when he finally spoke again,",
    "it came out harder than even he expected.",
    "Ten years, Richard.",
    "You were about to sell ten years of work, forty families' entire livelihoods,",
    "just to patch a hole that you dug yourself.",
    "And you were going to do it behind my back.",
    "Richard had no answer for that.",
    "Just one quiet request, almost a whisper.",
    "Give me a chance to fix this my own way.",
    "Marcus stood up. He gathered the papers off the table without another word,",
    "and said the only thing that actually made sense to him in that",
    "moment. No. Now I'm going to find out exactly who you've been talking to.",
    "Because this doesn't smell like just a personal debt anymore.",
    "This smells like something bigger.",
    "There was a long pause after that, neither of them speaking,",
    "the office suddenly feeling much smaller than it actually was.",
    "Richard finally asked the question that had clearly been eating at him the",
    "whole time. Are you going to tell everyone?",
    "The engineers, the board, all of it?",
    "Marcus didn't answer right away.",
    "Not because he didn't know, but because he genuinely hadn't decided yet,",
    "and he wasn't about to promise something he might not be able to",
    "keep. I don't know yet, he said honestly.",
    "But I know I'm not signing anything until I understand exactly what you",
    "got us into."
  ],
  "cap4": [
    "Marcus spent the next three days doing the one thing he had always",
    "done better than anyone else at Nortech: investigating systems,",
    "not people. Numbers don't lie, even when the people behind them do.",
    "He asked the company's legal team to quietly dig up everything they could",
    "find on that outside consulting firm,",
    "and on the investor group that had sent the buyout proposal in the",
    "first place. What came back didn't sit right at all.",
    "The consulting firm's name didn't exist in any public record before eight months",
    "ago. Its registered address turned out to be a single rented room above a",
    "print shop, with no listed employees, no website worth mentioning, nothing.",
    "And the investor group that wanted to buy Nortech,",
    "the very same one whose proposal was sitting in Richard's inbox,",
    "shared a founding partner with that exact same shell consulting firm.",
    "This wasn't just Richard's personal financial mess anymore.",
    "This was a scheme, carefully built, one piece at a time.",
    "Marcus called the company's lawyer in the middle of the night,",
    "still sitting alone at his desk, the office dark around him.",
    "They don't actually want to buy Nortech for the product, Marcus said,",
    "his voice low. They want the source code.",
    "They want the pricing algorithm we spent six years refining, line by line.",
    "Once that contract gets signed, they own full rights to the technology, permanently.",
    "It wouldn't even matter if the company folded a year later.",
    "They'd already have what they came for.",
    "The lawyer confirmed exactly what Marcus had already started to suspect.",
    "The intellectual property clause buried inside the sale contract was written far too",
    "broadly to be an accident.",
    "It wasn't sloppy legal language.",
    "It was deliberate. Someone had written it knowing precisely what they intended to take.",
    "Richard hadn't just been quietly settling a private debt this whole time.",
    "Without fully realizing it, or maybe realizing it far too late to stop it,",
    "he had become the open door for a group trying to legally, quietly,",
    "steal a decade of work that Nortech had built from nothing.",
    "This changed everything. It wasn't about forgiving a friend for one bad mistake anymore.",
    "It was about protecting forty families who depended on their paychecks,",
    "ten years of work that started in a garage,",
    "and a piece of technology that never belonged to just one person to",
    "give away. Four days were left before the buyout offer expired for good.",
    "Before he took any of it to the lawyer,",
    "Marcus made one more call, to a woman named Diane,",
    "an early investor who had mentored both of them back when Nortech was",
    "barely more than an idea on a whiteboard.",
    "He hadn't spoken to her in almost two years.",
    "She listened to the entire story without interrupting once.",
    "When he finished, she was quiet for a moment,",
    "then she said something he never forgot.",
    "You already know what you have to protect here, Marcus.",
    "The question isn't what Richard did.",
    "The question is what kind of company you want Nortech to still be,",
    "a year from now, once the dust settles.",
    "That single sentence stayed with him for the rest of the week.",
    "There was one more detail that kept bothering him,",
    "something small that almost got lost in all the paperwork.",
    "The shell consulting firm had opened its account at the exact same bank",
    "branch the investor group used for its own operating funds.",
    "Not the same city, not the same bank, the same branch.",
    "That kind of coincidence doesn't happen by accident, and Marcus knew it.",
    "Whoever had built this plan had been sloppy in exactly one place,",
    "and that one place was about to become the crack the entire scheme",
    "fell through."
  ],
  "cap5": [
    "Marcus had exactly two options in front of him now,",
    "and neither one of them was going to be easy.",
    "The first option: expose everything, completely, right away.",
    "Take every piece of evidence straight to the board.",
    "Call out Richard publicly, in front of everyone.",
    "Cancel the sale outright and sue the investor group for attempted fraud.",
    "It would be fast. It would be final.",
    "And it would destroy, in one single afternoon, not just Richard's career,",
    "but ten years of friendship,",
    "in front of every single person the two of them had built this",
    "company with. The second option: handle it from the inside, quietly.",
    "Confront the investor group directly, without turning it into a public scandal.",
    "Renegotiate the terms on his own.",
    "Give Richard a real way out,",
    "one that would pay off the debt without handing over the company,",
    "but that forced him to fully own, in writing,",
    "every bit of damage he had caused.",
    "Late that night, Marcus found himself remembering something Richard had actually said,",
    "years earlier, back when Nortech was still just two guys and a folding table.",
    "You don't build a company like you build a building,",
    "Richard had told him. You build it like you build trust.",
    "Slowly, one brick at a time.",
    "And it all comes crashing down at once if somebody pulls the wrong",
    "one out. Marcus made his decision.",
    "He wasn't going to be the person who brings the entire building down",
    "just to prove that he'd been right all along.",
    "But he also wasn't going to protect the man who had put everyone",
    "else's future at risk to save himself.",
    "He picked up the phone and called the lawyer again.",
    "Set up a meeting, he said.",
    "With the investor group. The exact same meeting they'd already scheduled, for the signing.",
    "Except this time, I decide what actually gets signed.",
    "And that's the moment Marcus realized something.",
    "That meeting, the very same one that opened this entire story,",
    "the one with the cursor blinking silently over the words sign contract,",
    "was never the ending at all.",
    "It was simply the moment he had chosen, on his own terms,",
    "to turn the whole thing around.",
    "Only twenty-four hours were left now.",
    "He thought, too, about the forty people who worked there,",
    "people who had no idea any of this was happening.",
    "The engineer who had just bought her first apartment based on a stable",
    "paycheck. The support team lead who was six months from retirement.",
    "None of them had signed up to have their futures decided by somebody",
    "else's secret, and none of them deserved to lose everything over a mistake they had",
    "no part in making.",
    "That thought alone made the decision easier than he expected it to be."
  ],
  "cap6": [
    "Thirty seconds were left before the meeting started.",
    "Again. Same room. Same clock on the wall.",
    "Same cursor, waiting. Except this time, Marcus wasn't sitting there staring at a screen,",
    "wondering whether or not to click anything.",
    "He already knew, with total certainty, exactly what he was about to do.",
    "The investor group's representative walked in, opened his laptop,",
    "and calmly turned the screen toward Marcus, tapping the same familiar button.",
    "We just need your signature right here, and this whole thing is settled.",
    "Marcus didn't touch the laptop.",
    "He didn't even look at it.",
    "Before we do that, Marcus said, his voice steady,",
    "I need you to explain something to me first.",
    "Why does clause seven of this contract give your group full,",
    "permanent rights to our pricing algorithm,",
    "even if the company shuts down in under a year?",
    "Walk me through that. Nobody answered.",
    "The room went completely silent.",
    "And while we're at it, Marcus continued,",
    "calmly laying the printed documents on the table one by one,",
    "why does the consulting firm that received three hundred thousand dollars from our",
    "company's cash share a founding partner with the man sitting right there,",
    "on the right side of this table?",
    "The representative tried to talk his way around it.",
    "He stumbled. He couldn't. Marcus turned and looked at Richard directly.",
    "I know exactly why you did this.",
    "You were trying to patch a hole that turned into an avalanche,",
    "and I understand, more than you probably think I do,",
    "what it feels like to be terrified of losing everything you spent years",
    "building. But I'm not going to let Nortech pay the price for your fear.",
    "Not this time. This meeting is over, Marcus said, standing up.",
    "And if any of you try this same move with another company anywhere",
    "in this city,",
    "this entire file lands on a prosecutor's desk before you even make it",
    "back to your car. The investor group left without another word.",
    "Nobody argued. Richard stayed behind, alone in the room with Marcus.",
    "What happens to me now, Richard asked quietly, barely above a whisper.",
    "Now, you're going to pay back every single cent you took from this company,",
    "little by little, for as long as it takes.",
    "And you're going to keep working here.",
    "But you are never again deciding the fate of forty families by yourself.",
    "Trust, we can rebuild. Slowly.",
    "But the right way this time.",
    "Not blindly. For a moment, nobody in the room moved.",
    "The lead investor glanced at Richard,",
    "as if expecting him to jump in and defend the deal,",
    "but Richard just sat there, staring at the table, saying nothing at all.",
    "Word of what happened in that room got around the office by the",
    "following afternoon, the way these things always do, in quiet conversations by the coffee machine.",
    "Nobody cheered. Nobody celebrated.",
    "But there was a kind of relief in the building that hadn't been",
    "there in weeks,",
    "the sense that whatever had been wrong was finally, actually, being dealt with.",
    "The lead investor tried one last angle,",
    "offering to simply rewrite clause seven on the spot,",
    "right there at the table,",
    "if Marcus would just agree to keep moving forward with the rest of",
    "the deal. Marcus almost laughed.",
    "You wrote a contract designed to take our technology for free if the",
    "company failed, he said,",
    "and now you're offering me a better version of the same trap.",
    "I think we're done here.",
    "He closed his own folder, stood up, and didn't wait for a response."
  ],
  "cap7": [
    "Six months later, Nortech was still standing.",
    "Bigger, actually, than it had ever been before.",
    "The whole ordeal, as painful and messy as it was,",
    "pushed both partners to finally put real rules in place.",
    "No major decision without both signatures, no exceptions.",
    "An outside financial audit, twice a year, no matter how uncomfortable.",
    "And a small advisory board made up entirely of outsiders,",
    "people with no personal stake to protect, and nothing to hide.",
    "Richard stayed on at the company.",
    "Quieter now. More careful. Slowly paying back, month after month,",
    "a debt that had stopped being just about money a long time ago.",
    "A year after all of it,",
    "Nortech signed the biggest contract in its history,",
    "with a retail chain that operated in over two hundred stores.",
    "Marcus insisted the entire negotiation happen with both the new advisory board and",
    "Richard fully looped in from day one,",
    "no closed doors, no side conversations.",
    "It took longer than it used to.",
    "It also felt, for the first time in years, completely safe.",
    "Sometimes, late in the office,",
    "Marcus still thinks about that folder sitting on the table in front of",
    "the investor group, and how close everything had come to disappearing over a single signature.",
    "He doesn't regret how he handled it.",
    "He regrets, a little,",
    "that it took almost losing everything to learn a lesson that simple.",
    "People sometimes ask if Marcus ever fully forgave Richard.",
    "His answer is always the same.",
    "Forgiving someone and trusting them blindly again are two very different things,",
    "and only one of them was ever actually his to give.",
    "And Marcus, looking back on all of it,",
    "learned something the hardest way possible: trust without any kind of verification isn't",
    "really trust at all. It's just a bet you're making with someone else's future,",
    "and calling it faith.",
    "The most expensive decision of somebody's life isn't always the one that feels",
    "the most dramatic in the moment it happens.",
    "Sometimes, the real decision is much quieter than that.",
    "It's the choice to stop.",
    "To actually investigate.",
    "To decide calmly, even when everything around you, every instinct in your body,",
    "is screaming at you to rush.",
    "If there's one thing he'd want you to take from all this,",
    "it's this: the people you trust the most are exactly the people worth",
    "double-checking, not because you love them any less,",
    "but because real trust can survive being verified.",
    "It's the trust that can't survive a few honest questions that was never",
    "really trust to begin with.",
    "Thirty seconds were left before that meeting.",
    "That's how this whole story started.",
    "And today, whenever somebody asks Marcus how he knew exactly what to do in that",
    "room, he always gives them the same honest answer.",
    "I didn't know, he says.",
    "I just refused to rush a decision about something that took me ten",
    "years of my life to build.",
    "If you made it all the way here, thank you, genuinely,",
    "for watching this entire story from start to finish.",
    "If it was worth your twenty-five minutes,",
    "let me know down in the comments.",
    "And next week, there's another one waiting,",
    "with an ending I can promise you, you will not see coming."
  ]
} as const;
